### ISSUE TITLE
Implement data release date (data policy)

### ISSUE THREAD

**Issue by Stastein** [npolar/api.npolar.no#17]
Fra datapolitikken:

Beskyttelsesperioden skal datofestes, og bør normalt ikke settes til mer enn 2 år etter at datainnsamlingen er avsluttet. Innenfor rammene av de kontraktsvilkår og eksterne betingelser  som gjelder for prosjektet, kan beskyttelsesperioden gjøres lengre hvis det er nødvendig for å ivareta førsteretten til publisering. Seksjonsleder er ansvarlig for å sette frigivelsesdato og kan utvide  beskyttelsesperioden inntil 4 år etter at datainnsamlingen er avsluttet. Utvidelse av beskyttelsesperioden ut over 4 år skal kun gis unntaksvis og må godkjennes av avdelingsdirektør. 

Når  beskyttelsesperioden er utløpt, eller når ingen beskyttelsesperiode er datofestet, vil data som er ferdig prosessert, dokumentert og lagret ved instituttet være åpent tilgjengelige fra data.npolar.no.

**Comment by Stastein** [comment]
A workable solution has to be implemented. Date-triggered change from "draft" to "complete"?

**Comment by cnrdh** [comment]
I've experienced that the date is a moving target, ie. auto-opening could make some people unhappy.

**Comment by cnrdh** [comment]
Finally, this is implemented via a nightly migration.
