### ISSUE TITLE
Broken schema links

### ISSUE THREAD

**Issue by baelter** [npolar/api.npolar.no#69]
http://api.npolar.no/schema/dataset-1-0.0.pre should be http://api.npolar.no/schema/dataset-1.0.0.pre.json

**Comment by baelter** [comment]
See http://api.npolar.no/dataset/79c539d0-c67c-5ae1-a973-ce282fe46abf

**Comment by cnrdh** [comment]
No, the URI is wrong, it should be
http://api.npolar.no/schema/dataset-1.0.0.pre

**Comment by cnrdh** [comment]
I'll migrate all datasets to the correct URI

**Comment by cnrdh** [comment]
Done
