### ISSUE TITLE
Suggest alerting user of possible duplicate entry

### ISSUE THREAD

**Issue by paulflakstad** [npolar/api.npolar.no#71]
Suggest alerting user of possible duplicate entry, e.g. if a publication of identical type, and the same / almost the same title exists.

Background: I've come across several duplicate publication entries. A likely cause can be explained by the following scenario: A user is missing a publication in some list where it was expected to appear. (This happens quite often, due to wrong year / draft / visibility settings.) Assuming it's missing because it's not registered, the user then re-registers it, creating a duplicate.

**Comment by cnrdh** [comment]
Absolutely a problem, there a tons...

**Comment by cnrdh** [comment]
Even more duplicates found. Closing here, since it's not fixable in the API core

Moved to

* https://github.com/npolar/npdc-publication/issues/1
* https://github.com/npolar/work/issues/80
