### ISSUE TITLE
Support old attachment syntax when upgrading to the new file backend

### ISSUE THREAD

**Issue by RDux** [npolar/api.npolar.no#74]
Currently there is a middlware that redirects requests with "**?attachment=filename**" the right couch url. To support the old syntax we should update the [middleware](https://github.com/npolar/api.npolar.no/blob/master/lib/npolar/rack/attachment_downloader.rb) to point to the new file backend. 

An alternative is to remove the middlware and add an nginx rewrite rule. Nginx seems to be able to rewrite url's with query params and since there already is a nginx rule tied to the current setup replacing the middlware with just an nginx rule might be better.

**Comment by cnrdh** [comment]
Not important, see #73
