### ISSUE TITLE
Filter/facets 'approved' on /placename endpoint

### ISSUE THREAD

**Issue by Stazia** [npolar/api.npolar.no#75]
Good day,
My name is Anastasia and I work with placenames in NRK, Yr-project. 
We have been using npolar api for quite some time to get placenames data from Polarinstituttet. 'filter-approved=true' has been used in the uri like that 'http://api.npolar.no/placename/?q=&filter-approved=true&sort=location+asc,ident+asc&format=json'. We have experienced lately that this filter is no longer working. I see under 'facets' on the '/placename'-endpoint that there is 'status'-filter. So I wonder if this 'approved' filter has been changed or removed? It looks like it could have been replaced by 'status'-filter...
Hope for your answer!
Regards, Anastasia

**Comment by cnrdh** [comment]
God dag Anastasia.

The legacy service you have been using has been replaced with a GeoJSON API for Placenames. You're on it, please use fiter-status=official now:
http://api.npolar.no/placename/?q=&filter-status=official&format=geojson

**Comment by cnrdh** [comment]
Here's the URI you probably want, if you want to limit the number of fields:
http://api.npolar.no/placename/?q=&filter-status=official&format=geojson&fields=name.@value,area,type,geometry,terrain,id,ident&sort=-area&filter-area=Svalbard|Dronning+Maud+Land|Jan+Mayen|Bouvet%C3%B8ya|Peter+I+%C3%98y&limit=5

Just change to `limit=all`l to receive all names.

Feel free to ping back if you have more questions.

Best wishes
Conrad

**Comment by Stazia** [comment]
Ok, will do! 
Thank you for the quick response!

Regards, Anastasia

**Comment by Stazia** [comment]
Hei again,
There is a placename that has the same terrain in norwegian and english (english word 'scree'):  http://api.npolar.no/placename/?q=&filter-ident=18930&filter-status=official&format=geojson. I suppose it should be 'ur' in norwegian?
Regards, Anastasia

**Comment by cnrdh** [comment]
Good catch, thanks. Fixed now. (Strange though, but the terrain strings are not a fixed vocabulary, so this sort of thing can occur.)

**Comment by cnrdh** [comment]
Btw, check out our new [supercluster](http://npolar.github.io/placenames/demo/supercluster/) to see which areas the official names covers

**Comment by Stazia** [comment]
Ok, thank you!
/Anastasia

**Comment by Stazia** [comment]
Nice supercluster! :)

**Comment by Stazia** [comment]
Sorry to bother you again but I've found some more placenames that have english categories instead of norwegian.. These here have 'ice dome' instead of 'iskuppel'
http://api.npolar.no/placename/?q=&filter-terrain.nn=ice%20dome&filter-status=official&sort=location+asc,ident+asc&format=json

/Anastasia

**Comment by Stazia** [comment]
And also some placenamnes with 'lake' terrain: 
http://api.npolar.no/placename/?q=&filter-terrain.nn=lake&filter-status=official&format=json
In norwegian should be 'vatn'.

/Anastasia

**Comment by cnrdh** [comment]
Thanks again, there's something awry here:
http://api.npolar.no/placename/?q=&facets=terrain.nn

**Comment by cnrdh** [comment]
Ikkje bra nynorsk(!)

bay (7) lake (7) place name (6) ice dome (5) islet, skerry, rock (5) area, district, region (3) shore, coast (2) slope (2) fiord house (1) peninsula (1) placename (1) plain, expanse, plateau (1) strait, sound (1) submarine slope (1)

**Comment by Stazia** [comment]
No:) But there are nynorsk versions there like lake - vatn, bay - vik, ice dome - iskuppel etc.. seems that some placenames have been registered with english terrain instead of nynorsk?

**Comment by cnrdh** [comment]
Cleaning these right now.
