### ISSUE TITLE
Missing idents on some placenames (Svaldbard, Dronning Maud Land)

### ISSUE THREAD

**Issue by Stazia** [npolar/api.npolar.no#76]
Good day!

My name is Anastasia and I work with placenames in NRK, Yr-project.
We have noticed that some placenames at Polarinstituttets data/api miss idents. So I wonder if it should be there? We use these idents to generate Ids for imported places from Polarinstituttet that is how we noticed - our import code failed.
I have noted following places:
c5b8df20-a8c4-457e-ac9d-9b119914e4f2 - Svaldbard - Håhellerfjella - fjell
(http://api.npolar.no/placename/?q=&filter-id=c5b8df20-a8c4-457e-ac9d-9b119914e4f2&filter-status=official&format=geojson f.eks.)
f97d67fc-579d-4607-8c4f-868a8bacc54a - Dronning Maud Land - Palisaden  - fjell
0ee66a26-2fb2-406d-9757-89982efc3dee - Dronning Maud Land - Glitrefjella - fjell
ffb1b34e-84e7-4170-926c-54f00ffdff55 - Dronning Maud Land - Vendefjella - fjell
d81c64cd-7028-4b0b-81c9-fc27d92d1245 - Dronning Maud Land - Smedfjella - fjell
ffb1b34e-84e7-4170-926c-54f00ffdff55 - Dronning Maud Land - Flokken - fjell
dc82e955-176a-4880-ad09-66d8c9b49a83 - Dronning Maud Land - Korkfjella - fjell
777fc024-dd56-4ee0-ab6b-b2dcf43c9ed3 - Dronning Maud Land - Gjelsida - fjell
fc9e5234-3ef7-46b3-901a-0474957c3fdb - Dronning Maud Land - Skirfjella - fjell
50126e14-4827-4d8c-81ff-173584385de6 - Dronning Maud Land - Iskampane - fjell
3cbd13ff-a2f4-490e-9294-b2b9f57bab98 - Dronning Maud Land - Nordryggane - fjell
3fe9a8be-e697-482c-9473-80c0ed98abe6 - Dronning Maud Land - Hjelmtoppane - fjell
f7ba0794-cef7-4e36-9810-2e864254b611 - Dronning Maud Land - Speidarane - fjell
ef116dd8-a0bd-44ff-a7f0-581b493bcdd8 - Dronning Maud Land - Midtfjella - fjell

Hope for your response!

Regards, Anastasia

**Comment by cnrdh** [comment]
Right.
The "idents" are legacy identifiers so new names won't have those, but as you see they have UUIDs so I suggest you use those.

The UUID (found in the "id" property) is also used in the URI of each name
* http://api.npolar.no/placename/c5b8df20-a8c4-457e-ac9d-9b119914e4f2

For reference, these are the only names without ident  at the moment
id	name.@value
c5b8df20-a8c4-457e-ac9d-9b119914e4f2	Håhellerfjella
f97d67fc-579d-4607-8c4f-868a8bacc54a	Palisaden
0ee66a26-2fb2-406d-9757-89982efc3dee	Glitrefjella
d81c64cd-7028-4b0b-81c9-fc27d92d1245	Smedfjella
ffb1b34e-84e7-4170-926c-54f00ffdff55	Vendefjella
69bbaf7f-e793-4108-be77-8967d90f8cb7	Yttersida
d91c3411-f924-4faf-abca-b99383e71e44	Flokken
dc82e955-176a-4880-ad09-66d8c9b49a83	Korkfjella
777fc024-dd56-4ee0-ab6b-b2dcf43c9ed3	Gjelsida
fc9e5234-3ef7-46b3-901a-0474957c3fdb	Skirfjella
f83d9e71-991d-4587-b998-fb614f414f33	Vindfjella
50126e14-4827-4d8c-81ff-173584385de6	Iskampane
3cbd13ff-a2f4-490e-9294-b2b9f57bab98	Nordryggane
3fe9a8be-e697-482c-9473-80c0ed98abe6	Hjelmtoppane
f7ba0794-cef7-4e36-9810-2e864254b611	Speidarane
ef116dd8-a0bd-44ff-a7f0-581b493bcdd8	Midtfjella

**Comment by cnrdh** [comment]
Seems to match your list...

**Comment by Stazia** [comment]
Ok. Thank you for your response!
Does that mean that there will be no 'idents' in the future? You will only use Ids?

**Comment by cnrdh** [comment]
We've kept the legacy idents so that any links in the wild, like those from
https://www.yr.no/sted/Norge/Svalbard/Grumantbyen/ would still work.

But any new names won't have idents, so I think you should rather use the id like
https://placenames.npolar.no/placename/4543a914-7609-5ed8-9a28-0d631292d052

(sorry, there's a SSL-certificate problem at the moment)

**Comment by Stazia** [comment]
Ok. Thank you for your reply!
Regards, Anastasia
