### ISSUE TITLE
Question about "title_variants"

### ISSUE THREAD

**Issue by Stazia** [npolar/api.npolar.no#77]
Good day to you,
My name is Anastasia and I work with placenames in NRK, Yr-project.
I have been working with adjusting our "Placenames-solution" to changes made to api.npolar lately. I have a question about "title_variants" that have been there before at /placename endpoint. Just wonder if they are completely away or can be found at some other endpoint?
Thank you beforehand!
Regards, Anastasia

**Comment by cnrdh** [comment]
Hi, sorry for the late reply, been in the field.

There is now a relations block that contains "replaces" and "replaced_by":

See e.g. http://api.npolar.no/placename/770906ef-6705-54fd-8fab-07d7d8cc359e
```json
"relations": {
"replaces": [
{
"name": "Čebysevbreen",
"@id": "022e4189-b887-528c-ae9f-b8ebd9f46288"
},
{
"name": "Gl. Tchebychev",
"@id": "81f79951-d652-5649-ae45-a1edd2acc739"
},
{
"name": "Tsjebysjovbreen",
"@id": "9a4e6e8a-c770-5730-945c-c4d7ae272838"
}
],
```

**Comment by cnrdh** [comment]
The @id property means that it's a URI, in this case relative so that you will find  more details on Tsjebysjovbreen by following http://api.npolar.no/placename/9a4e6e8a-c770-5730-945c-c4d7ae272838

**Comment by Stazia** [comment]
Ok, I see. Thank you for your reply!
/Anastasia

**Comment by Stazia** [comment]
Sorry to bother you again, but I have found some places that have a field for "same_as", have some examples here:

 - http://api.npolar.no/placename/?q=&filter-ident=902219&filter-status=official&format=geojson
   (http://api.npolar.no/placename/3385e714-0441-59f1-ad42-1305c4b89985) - "same_as" (5c49cd33-8951-5081-b4c4-d9e1e6d3adef) is status standardised
 - http://api.npolar.no/placename/?q=&filter-ident=901356&filter-status=official&format=geojson 
   (http://api.npolar.no/placename/dde4363a-4dfa-5f72-bf68-2d0fe27ef387) - "same_as" is status standardised
 - http://api.npolar.no/placename/?q=&filter-ident=901263&filter-status=official&format=geojson
   (http://api.npolar.no/placename/22477cd4-cbe0-5800-9712-bff8a3d2fd99) - "same_as"(3f39f1e1-6c06-5b8e-9817-189a0a83bb40) is status historical
 - http://api.npolar.no/placename/?q=&filter-ident=901396&filter-status=official&format=geojson
(http://api.npolar.no/placename/5af5af7a-19ae-5f15-a89a-2c02e76736b2) - "same_as" (8ce99a22-3943-5c24-8568-5f29b31af69d) is status other

Are these alternative placenames? some with historical status should be "replaces"?

/Anastasia

**Comment by cnrdh** [comment]
You are touching something rather complicated here.

In the Norwegian Arctic (Svalbard, Jan Mayen) the names on land are controlled by NP and the currently approved names are marked with status "official", and we are able to say that the current name replaces the historical name.

In Antarctica, we don't control the names, so we use "same as" relation to indicate a relation in either way (replaces or is replaced by or is alternative form in another language or another country).

**Comment by cnrdh** [comment]
In Antarctica we don't control the names, so we use "same as" relation to indicate a relation in either way (replaces or is replaced by or is alternative form in another language or in another country). 

See http://www.scar.org/cga

That said, I'm not sure if I understand the question/your problem here.

**Comment by Stazia** [comment]
Ok. Thank you for your reply!
I just trying to understand the difference of these fields (replaces vs same_as). Since before we captured all the alternative names for a placename (title_variants). It's rather clear now:)

Regards, Anastasia

**Comment by Stazia** [comment]
Accidentally closed the issue.. but I got all the questions answered from you now:)
